apiVersion: apps/v1
kind: Deployment
metadata:
  name: magnezoo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: magnezoo
      version: stable
  template:
    metadata:
      labels:
        app: magnezoo
        version: stable
    spec:
      containers:
        - name: magnezoo
          image: registry.uniproject.jp/nnn/magnezoo:0.2.0
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: magnezoo-secret
          volumeMounts:
            - name: app-image-storage
              mountPath: /app/public/img/posts
            - name: app-avater-storage
              mountPath: /app/public/img/users
          readinessProbe:
            httpGet:
              path: /
              port: 3000
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      imagePullSecrets:
        - name: internal-harbor
      volumes:
        - name: app-image-storage
          persistentVolumeClaim:
            claimName: app-image-pvc
        - name: app-avater-storage
          persistentVolumeClaim:
            claimName: app-avater-pvc
