apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  annotations:
    cert-manager.io/cluster-issuer: le-cf-production
spec:
  ingressClassName: nginx
  rules:
    - host: magnezoo.unipro-n.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: magnezoo
                port:
                  number: 80
  tls:
    - hosts:
        - magnezoo.unipro-n.com
      secretName: magnezoo-site-dashboard-tls
