name: magnezoo
services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: magnezoo_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: magnezoo_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://magnezoo_user:securepassword@postgres:5432/magnezoo_db
    depends_on:
      - postgres
    networks:
      - magnezoo
volumes:
  db_data:

networks:
  magnezoo:
    driver: bridge
