import type { Metadata } from "next";
import "../globals.css";
import { headers } from "next/headers";
import { forbidden, unauthorized } from "next/navigation";
import Sidebar from "@/components/admin/Sidebar";
import { auth } from "@/lib/auth";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });
  if (!session) {
    unauthorized();
  }
  if (session.user.role !== "admin") {
    forbidden();
  }
  return <Sidebar user={session.user}>{children}</Sidebar>;
}
